config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :topics do
    resources :comments
  end
  root 'topics#index'
  get 'add/' => 'admin#new'
  post 'add/create'=>'admin#create'
    post 'add/demote'=>'admin#demote'

  resources :links do
  member do
    get "like", to: "links#upvote"
    get "dislike", to: "links#downvote"
  end
end
  # The priority is based upon order of exitcreation: first created -> highest priority.
  # See how all your routes lay out with "rake routes".

  # You can have the root of your site routed with "root"
  # root 'welcome#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  validates :link, presence: true
  acts_as_votable
has_many :comments
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:edit,:update, :destroy, :create]
 load_and_authorize_resource
  # GET /topics
  # GET /topics.json
  def index
    @topics = Topic.all
    end

  # GET /topics/1
  # GET /topics/1.json
  def show
    @comments=  @topic.comments 
  end

  # GET /topics/new
  def new
    @topic = Topic.new
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics
  # POST /topics.json
  def create
    
    respond_to do |format|
       @topic = Topic.new(topic_params)
        require 'open-uri'
      source = open(@topic.link).read
            
      tmp = Pismo::Document.new(@topic.link)
      @topic.title=tmp.title
      @topic.summary=tmp.lede
        @topic.description=  Readability::Document.new(source).content
        @rbody = Readability::Document.new(source, :tags => %w[div p img a], :attributes => %w[src href], :remove_empty_nodes => false)
        @topic.picture= @rbody.images[0]
      if @topic.save
        format.html { redirect_to edit_topic_path(@topic), notice: 'Change the title and summary of the article if it\'s not appropriate and preview the complete description ' }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
    @topic.title=topics_params['title']
    @topic.summary=topics_params['summary']
    @topic.save
    respond_to do |format|
      if @topic.update(topics_params)
        format.html { redirect_to @topic, notice: 'Topic was successfully created/updated.' }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
 def destroy
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topic_params
      params.require(:topic).permit( :link)
    end
def topics_params
      params.require(:topic).permit(:title, :summary)
    end
end
 

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_editform.html.erb
<%= simple_form_for(@topic) do |f| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% @topic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%t=false%>
  <% if @topic.link != nil %>
    <%= f.input :title %>
  <%t=true%>
  <%end%>
      <%= f.input :summary %>
Link: <%=link_to @topic.link,@topic.link%></br>
 <%if t==true%>
    <%= f.button :submit,"save"%>
    <%else%>
    <%= f.button :submit,"next"%>
    <%end%>
<% end %>

app/views/topics/_form.html.erb
<%= simple_form_for(@topic) do |f| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% @topic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.input :link , :placeholder => "http://www."%>
     <%= f.button :submit,"next"%>
<% end %>

app/views/topics/edit.html.erb
<div class="well">
<h1>Editing topic</h1>
<%= link_to 'Delete', @topic, method: :delete, :class => 'btn  btn-danger'  %>

<%= render 'editform' %>
</div>
<br><br>
<h3>Content To Be Displayed</h3>
<div class='well'>
    <div class="row">
  <div class="col-xs-1 col-md-4"></div>
  <div class="col-xs-1 col-md-4">

 <%if @topic.picture?%>
  <%= link_to image_tag(@topic.picture,size: "400x320"),@topic.picture  %>
              <%else%>
                <%= image_tag('http://img2.wikia.nocookie.net/__cb20130511180903/legendmarielu/images/b/b4/No_image_available.jpg',size: "400x320")%>
              <%end%>    </div>
      <div class="col-xs-1 col-md-4"></div>

    </div>
     <div class="row">
  <div class="col-xs-0 col-md-1"></div>
  <div class="col-xs-0 col-md-10">
    <%= @topic.description.html_safe%>
    </div>
       <div class="col-xs-0 col-md-1"></div>

    </div>
</div>

app/views/topics/index.html.erb
<% @topics.each do |topic| %>
<div class="panel panel-default">
      
      
      
  <div class="panel-heading">
      
      
      
    <div class="row">
      
      
      
      <div class="col xs-0 col-sm-0 col-md-3">
           <% if user_signed_in?%>
            <% if current_user.voted_up_on? topic  %>
                <%= link_to(like_link_path(topic), class: "btn btn-info") do %>
                <%=topic.get_upvotes.size%> <i class="fa fa-thumbs-o-up fa-1x " ></i>  
                <% end %>
                <%else%>
                <%= link_to(like_link_path(topic), class: "btn btn-default") do %>
                <%=topic.get_upvotes.size%> <i class="fa fa-thumbs-o-up fa-1x " ></i>  
                <% end %>
                <%end%>
            <% if current_user.voted_down_on? topic %>
                <%= link_to(dislike_link_path(topic), class: "btn btn-danger") do %>
                <i class="fa fa-thumbs-o-up fa-1x fa-rotate-180" ></i> <%=topic.get_downvotes.size%>
                <% end %>
                <%else%>
                <%= link_to(dislike_link_path(topic), class: "btn btn-default") do %>
                <i class="fa fa-thumbs-o-up fa-1x fa-rotate-180" ></i> <%=topic.get_downvotes.size%>
                <% end %>
            <%end%>
             
        <%else%>
          <%= link_to(root_path, class: "btn btn-info disabled") do %>
                <%=topic.get_upvotes.size%> <i class="fa fa-thumbs-o-up fa-1" ></i> 
                <% end %>
                <%= link_to(root_path, class: "btn btn-danger disabled") do %>
                <i class="fa fa-thumbs-o-up fa-1x fa-rotate-180" ></i> <%=topic.get_downvotes.size%>
                <% end %>
        <%end%>
      </div>
      
      <div class="col-xs-0 col-sm-5" onclick="location.href='topics/<%=topic.id%>';">
<center><h4><strong><%= topic.title %></strong></h4></center>
      </div>
      <div class="col-xs-0 col-sm-2">
        <% if can? :update, topic %>
        <%= link_to 'Edit', edit_topic_path(topic), :class => 'btn  btn-warning'  %>
        <% end %>
      </div>
      <div class="col-xs-0 col-sm-2">
            <% if can? :delete, topic %>
              <%= link_to 'Delete', topic, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn  btn-danger'  %>
            <% end %>
      </div>
    </div>
    
    
  </div>
  
  
  <div class="panel-body" onclick="location.href='topics/<%=topic.id%>';">
  <div class="row">
      <div class="col-xs-0 col-sm-4 col-md-4"></div>
      <div class="col-xs-0 col-sm-4 col-md-4">

        <div class="img-thumbnail">
          <center>
          <%if topic.picture?%>
            <%= image_tag(topic.picture, size: "200x120")  %>
          <%else%>
            <%= image_tag('http://img2.wikia.nocookie.net/__cb20130511180903/legendmarielu/images/b/b4/No_image_available.jpg',size: "200x120")%>
          <%end%></center>
          
      </div></div>
      <div class="col-xs-0 col-sm-4 col-md-3"></div>

    </div>
    
    <div class="row">
      <div class="col-md-1 col-xs-1"></div>
        <div class="col-md-10 col-sm-10" >

          <% if topic.summary==nil %>
       <center>   No Description Available</center>
       <% elsif topic.summary.length <3%>
              <center>   No Description Available</center>

          <%else%>
         <center> <%=topic.summary%>....</center>
         <%end%>
        </div>
        <div class="col-md-1 col-sm-1"></div>
      </div>
      
      
      
    </div>



</div>
<% end %>

app/views/topics/new.html.erb
<div class="well">
<h1>New topic</h1>
<%= render 'form' %>
</div>

app/views/topics/show.html.erb
    <div class="panel panel-default">
      <div class="panel-heading">
  
          <h3><strong><bold>
      <center> <%= @topic.title %></center>
  </bold></strong></h3>
    
    
          
              
              </div>

   <div class="panel-body" >
        <div class="row">
           <div class="colxsm-0 col-sm-1 col-md-1">
        <% if user_signed_in?%>
            <% if current_user.voted_up_on? @topic  %>
                <%= link_to(like_link_path(@topic), class: "btn btn-info") do %>
                <%=@topic.get_upvotes.size%> <i class="fa fa-thumbs-o-up fa-2x " ></i>  
                <% end %>
                <%else%>
                <%= link_to(like_link_path(@topic), class: "btn btn-default") do %>
                <%=@topic.get_upvotes.size%> <i class="fa fa-thumbs-o-up fa-2x " ></i>  
                <% end %>
                <%end%>
            <% if current_user.voted_down_on? @topic  %>
                <%= link_to(dislike_link_path(@topic), class: "btn btn-danger") do %>
                <i class="fa fa-thumbs-o-up fa-2x fa-rotate-180" ></i> <%=@topic.get_downvotes.size%>
                <% end %>
                <%else%>
                <%= link_to(dislike_link_path(@topic), class: "btn btn-default") do %>
                <i class="fa fa-thumbs-o-up fa-2x fa-rotate-180" ></i> <%=@topic.get_downvotes.size%>
                <% end %>
                <%end%>
        <%else%>
         <%= link_to(root_path, class: "btn btn-info disabled") do %>
                <%=@topic.get_upvotes.size%> <i class="fa fa-thumbs-o-up fa-2x " ></i> 
                <% end %>
                <%= link_to(root_path, class: "btn btn-danger disabled") do %>
                <i class="fa fa-thumbs-o-up fa-2x fa-rotate-180" ></i> <%=@topic.get_downvotes.size%>
                <%end%>
        <%end%>
       
       </div>
</br></br></br></br></br></br></br>
          <div class="col-sm-6 col-md-10">
               <center> <%if @topic.picture?%>
  <%= link_to image_tag(@topic.picture,size: "400x320"),@topic.picture  %>
              <%else%>
                <%= image_tag('http://img2.wikia.nocookie.net/__cb20130511180903/legendmarielu/images/b/b4/No_image_available.jpg',size: "400x320")%>
              <%end%></center>
              </div>
                         <div class="colxsm-0 col-sm-1 col-md-1"></div>
          </div>
          </br></br>
          <div class="row">
            <div class="col-md-1 col-sm-1">
            </div>
              <div class="col-md-10 col-sm-10" >
                  <%= raw @topic.description %>

                </div>
           <div class="col-md1-1 col-sm-1">
            </div>
            
        </div>
            </div>

        
</div>
</br></br>
              <div class="col-sx-0 col-sm-1 col-md-1"></div>
              <div class="col-sx-0 col-sm-2 col-md-4">
          <% if can? :update, @topic %>
            <%= link_to 'Edit', edit_topic_path(@topic),  :class => 'btn btn-warning'  %>
            <% end %>
          </div>
          <div class="col-sx-0 col-sm-2 col-md-3">
            <%= link_to 'Show Original', @topic.link, :class => 'btn  btn-info'  %>

              </div>
                            <div class="col-sx-0 col-sm-1 col-md-1"></div>
          <div class="col-sx-0 col-sm-2 col-md-3">
            <% if can? :delete, @topic %>
            <%= link_to 'Delete', @topic, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn  btn-danger'  %>
            <% end %>
            
</div>
</br></br></br></br>
<div class="well">
<h3>Comments:</h3>

 <% @comments.each do |comment| %>
      <br/>
          <strong><u><%if comment.user.username == nil %>
            Anonymous
            <%elsif comment.user.username.length <3%>
                        Anonymous

          <%else%>
        <%=comment.user.username%>
          <%end%>
    </u></strong> : <%= comment.comment_body %>
    </br>
    <% if can? :destroy, comment %>
        <%= link_to 'Delete', [comment.topic, comment], method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn  btn-xs btn-danger'  %>
    <% end %>
    <br/>
 <%end%>
  <% if user_signed_in? %>
  </br></br></br>
  
  <h2>Add a comment:</h2>
  
  <%= simple_form_for([@topic, @topic.comments.build]) do |f| %>
    <%= f.input :comment_body %>
    <%t=true%>
    <%= f.button :submit %>
    <%end%>
    <% else %>
    <h5>Login to comment</h5>
    <%end%>
 
</div>