config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :topics do
    resources :comments
  end
  root 'topics#index'
  get 'add/' => 'admin#new'
  post 'add/create'=>'admin#create'
    post 'add/demote'=>'admin#demote'

  resources :links do
  member do
    get "like", to: "links#upvote"
    get "dislike", to: "links#downvote"
  end
end
  # The priority is based upon order of exitcreation: first created -> highest priority.
  # See how all your routes lay out with "rake routes".

  # You can have the root of your site routed with "root"
  # root 'welcome#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Share ideas...</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>



<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    <%= link_to 'Home', root_path, :class => "navbar-brand" %>
  </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      <li> <% if can? :create, Topic %>
        <%= link_to 'Add Topic', new_topic_path %>
        <% end %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
              <%if current_user.username == nil  %>
              <li><%= link_to 'edit profile', edit_user_registration_path %></li>
                <%elsif current_user.username.length  <3%>
                              <li><%= link_to 'edit profile', edit_user_registration_path %></li>

                <%else%>
                              <li><%= link_to current_user.username, edit_user_registration_path %></li>
<%end%>
            
          <li><%= link_to 'logout', destroy_user_session_path, method: :delete %></li>
          <%if current_user.admin?%>
              <li><%= link_to "Manage admins",add_path%></li>
          <%end%>
      <% else %>
           <li><%= link_to "Sign Up", new_user_registration_path %></li>
           <li><%= link_to "Sign In", user_session_path %></li>
      <% end %> 
      </ul>
    </div>
  </div>
</nav>

       <div class= "container">     
    <p class="notice"><%= notice %></p>
<%= yield %>
</div>

</body>
</html>